// AUTOMATICALLY GENERATED BY BUILDINC v0.1.100 TOOL
// LAST BUILD: 2022-09-13 16:04:26

#pragma once

#ifndef PIKUMODULESVERSION_BUILDNUMBER_HEADER_H
#define PIKUMODULESVERSION_BUILDNUMBER_HEADER_H

#include <cstdint>

namespace PikuModulesVersion
{
		 // You can modify major and minor
		constexpr uint32_t major = 0;
		constexpr uint32_t minor = 1;

		 // Do not modify these
		constexpr uint32_t build = 427;
		
		constexpr uint32_t version = major * 10000 + minor * 1000 + build;
		constexpr uint64_t random_seed = 0x91945e958ede08;
		
		constexpr char version_string[] = "v0.1.427";
		constexpr char build_time_string[] = "2022-09-13 16:04:26";
		constexpr char phrase[] = "lark-astound-shortwave";
		constexpr char calver[] = "2022.37.427";

		// Copy paste to import to your project
		/*
			constexpr auto major = PikuModulesVersion::major;
			constexpr auto minor = PikuModulesVersion::minor;
			constexpr auto build = PikuModulesVersion::build;
			constexpr auto version = PikuModulesVersion::version;
			constexpr auto random_seed = PikuModulesVersion::random_seed;
			
			constexpr auto version_string = PikuModulesVersion::version_string;
			constexpr auto build_time_string = PikuModulesVersion::build_time_string;
			constexpr auto phrase = PikuModulesVersion::phrase;
			constexpr auto calver = PikuModulesVersion::calver;
		*/
}
#endif // PIKUMODULESVERSION_BUILDNUMBER_HEADER_H

