// AUTOMATICALLY GENERATED BY BUILDINC v0.2.196 TOOL
// LAST BUILD (CMAKE): 2022-09-29 21:08:13

#pragma once

#ifndef PIKUMODULESVERSION_BUILDNUMBER_HEADER_H
#define PIKUMODULESVERSION_BUILDNUMBER_HEADER_H

#include <cstdint>

namespace PikuModulesVersion
{
		 // You can modify major and minor
		constexpr uint32_t major = 0;
		constexpr uint32_t minor = 1;

		 // Do not modify these
		constexpr uint32_t build = 1145;
		
		constexpr uint32_t version = major * 100000 + minor * 10000 + build;
		constexpr uint64_t random_seed = 0x8f8f1a9f4eb6cf37;
		
		constexpr char version_string[] = "v0.1.1145";
		constexpr char build_time_string[] = "2022-09-29 21:08:13";
		constexpr char phrase[] = "cough-rigging-account";
		constexpr char calver[] = "2022.39.1145";

		// Copy paste to import to your project
		/*
			constexpr auto major = PikuModulesVersion::major;
			constexpr auto minor = PikuModulesVersion::minor;
			constexpr auto build = PikuModulesVersion::build;
			constexpr auto version = PikuModulesVersion::version;
			constexpr auto random_seed = PikuModulesVersion::random_seed;
			
			constexpr auto version_string = PikuModulesVersion::version_string;
			constexpr auto build_time_string = PikuModulesVersion::build_time_string;
			constexpr auto phrase = PikuModulesVersion::phrase;
			constexpr auto calver = PikuModulesVersion::calver;
		*/
}
#endif // PIKUMODULESVERSION_BUILDNUMBER_HEADER_H

